# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: expense
#   region: us-east-1

# managedNodeGroups:
#   - name: expense
#     instanceType: m5.large
#     desiredCapacity: 3
#     spot: true

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense-ondemand
    instanceTypes: ["t3.medium"]
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    ssh:
      allow: false